[package]
name = "tips"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
sysinfo = "0.30"
directories = "5.0"
chrono = "0.4"